site_name: OnChain
nav:
  - OnChainTraits: ./OnChainTraits.md
  - ERC721oc: ./reference/ERC721oc.md
  - test:
    - MinimalTest: ./test/MinimalTest.md
    - RandomTest: ./test/RandomTest.md
  - Libs:
    - AssetBuilder: ./libs/AssetBuilder.md
    - MetadataBuilder: ./libs/MetadataBuilder.md
    - Base64Encoder: ./libs/Base64Encoder.md
    - Random: ./libs/Random.md
    - Constants: ./libs/Constants.md
    - OnChainDataStructs: ./libs/OnChainDataStructs.md
theme: readthedocs
